#!/usr/bin/env python3

#
# mplayer3
#
# Copyright (c) 2026, Chris McGimpsey-Jones (chrisjones.unixmen@gmail.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <https://www.gnu.org/licenses/>.
#

import os
import sys
import pwd
import shutil
import subprocess
from pathlib import Path

# --- Paths ---
APP_NAME        = "mplayer3"
INSTALL_TARGET  = Path("/usr/local/bin") / APP_NAME
SOURCE_SCRIPT   = Path(__file__).parent / APP_NAME

# cache-util ((>v1.4) used by mplayer3 by default)
CACHE_PLAYER_NAME   = "utils/cache-util"
CACHE_PLAYER_PARENT = Path(__file__).parent / "utils"
CACHE_PLAYER_PKG    = "cache-util"
CACHE_PLAYER_SOURCE = Path(__file__).parent / CACHE_PLAYER_NAME
CACHE_PLAYER_DIR    = Path("/usr/local/lib/mplayer3/utils")
CACHE_PLAYER_TARGET = CACHE_PLAYER_DIR / CACHE_PLAYER_PKG

# mplayer-bin source tree and build dir
MPV3_SRC_PKG    = "mplayer3-bin"
MPV3_SRC_DIR    = Path(__file__).parent / "bin"
MPV3_BUILD_DIR  = MPV3_SRC_DIR / "build"

# Resolve real user home even when run via sudo
sudo_user = os.environ.get("SUDO_USER")
if sudo_user:
    _pw = pwd.getpwnam(sudo_user)
    REAL_HOME = Path(_pw.pw_dir)
    REAL_UID  = _pw.pw_uid
    REAL_GID  = _pw.pw_gid
else:
    REAL_HOME = Path.home()
    REAL_UID  = os.getuid()
    REAL_GID  = os.getgid()

CONF_DIR        = REAL_HOME / ".config" / "mplayer3"
MPV_CONF_FILE   = CONF_DIR / "mplayer3.conf"
INPUT_CONF_FILE = CONF_DIR / "input.conf"

# --- Marker (fingerprint to prevent duplicate appends) ---
MPLAYER3_MARKER = "# --- mplayer3 compatibility settings ---"

# --- Config file contents ---
MPV_CONF = """\
# mplayer3 config
# Generated by install_mplayer3.py

# Video and Hardware
vo=gpu
hwdec=auto
opengl-swapinterval=1
border=no
autofit=1280
audio-display=no

# Intel users: disable hwdec-auto (above) > enable hwdec-vaapi (below)
#hwdec=vaapi

# Audio
volume=100
volume-max=200

# OSD
osd-level=1
osd-font='Sans'
osd-font-size=30
osd-color='#CCFFFFFF'
osd-border-color='#99000000'
osd-bar-align-y=0.7
osd-bar-h=2
osd-bar-w=60

# Useless and hostile output suppression
msg-level=vo/gpu/libplacebo=error
"""

INPUT_CONF = """\
# mplayer3 keybindings
# Generated by install_mplayer3.py

ENTER   cycle fullscreen
ESC     quit
SPACE   cycle pause
f       cycle fullscreen
m       cycle mute
UP      add volume 5
DOWN    add volume -5
LEFT    seek -10
RIGHT   seek 10
PGUP    seek 600
PGDWN   seek -600
.       frame-step
,       frame-back-step
"""

# --- Helpers ---
def append_if_missing(path, content, marker):
    """
    For mplayer3.conf:
      - If file does not exist: create it fresh.
      - If file exists but marker is absent: append our block once, skipping duplicate option lines.
      - If file exists and marker is present: skip entirely (no duplicates).
    """
    if path.exists():
        existing = path.read_text()
        if marker in existing:
            print(f"  [SKIP]     {path}  (mplayer3 settings already present)")
        else:
            # Filter out any option lines that already exist in the file
            existing_lines = set(existing.splitlines())
            filtered_lines = []
            for line in content.splitlines():
                # Always keep comments, blank lines, and marker lines as-is
                if line.startswith("#") or line.strip() == "":
                    filtered_lines.append(line)
                # Only add option lines if not already present in the file
                elif line not in existing_lines:
                    filtered_lines.append(line)
            filtered_content = "\n".join(filtered_lines)
            with open(path, "a") as f:
                f.write(f"\n{filtered_content}\n")
            print(f"  [APPENDED] {path}  (mplayer3 settings added to existing file)")
    else:
        with open(path, "w") as f:
            f.write(content)
        print(f"  [CREATED]  {path}")

def write_if_missing(path, content):
    """
    For input.conf:
      - Keybindings are personal. Never overwrite an existing file.
      - Only create if it does not exist at all.
    """
    if path.exists():
        print(f"  [SKIP]     {path}  (already exists, keybindings not overwritten)")
    else:
        with open(path, "w") as f:
            f.write(content)
        print(f"  [CREATED]  {path}")

# --- Build helpers ---
def _demote_to_user():
    """preexec_fn used by run_as_user: drop root -> SUDO_USER for the child process."""
    os.setgid(REAL_GID)
    os.setuid(REAL_UID)

def run_as_user(cmd, cwd, label):
    """
    Run a command as the original invoking user (SUDO_USER), not as root.
    Falls back to current user if SUDO_USER is unset.
    Streams stdout/stderr live. Exits the installer on failure.
    """
    print(f"  [{label}] $ {' '.join(cmd)}   (as user: {sudo_user or os.environ.get('USER', 'current')})")

    env = os.environ.copy()
    if sudo_user:
        env["HOME"]    = str(REAL_HOME)
        env["USER"]    = sudo_user
        env["LOGNAME"] = sudo_user
        # Keep PATH but ensure /usr/local/bin and /usr/bin are present
        env.setdefault("PATH", "/usr/local/bin:/usr/bin:/bin")

    try:
        if sudo_user and os.geteuid() == 0:
            result = subprocess.run(cmd, cwd=str(cwd), env=env, preexec_fn=_demote_to_user)
        else:
            result = subprocess.run(cmd, cwd=str(cwd), env=env)
    except FileNotFoundError as e:
        print(f"  [ERROR] Command not found: {e}")
        sys.exit(1)

    if result.returncode != 0:
        print(f"  [ERROR] {label} step failed (exit code {result.returncode}).")
        print(f"          Make sure all mpv3 build dependencies are installed.")
        sys.exit(result.returncode)

def run_as_root(cmd, cwd, label):
    """Run a command as root (the current euid). Streams output live."""
    print(f"  [{label}] $ {' '.join(cmd)}   (as root)")
    try:
        result = subprocess.run(cmd, cwd=str(cwd))
    except FileNotFoundError as e:
        print(f"  [ERROR] Command not found: {e}")
        sys.exit(1)

    if result.returncode != 0:
        print(f"  [ERROR] {label} step failed (exit code {result.returncode}).")
        sys.exit(result.returncode)

def preflight():
    errors = []
    if os.geteuid() != 0:
        errors.append("Must be run as root. Use: sudo install_mplayer3.py")
    if not SOURCE_SCRIPT.exists():
        errors.append(f"Source script '{APP_NAME}' not found in the same directory as this installer.")
    if not CACHE_PLAYER_SOURCE.exists():
        errors.append(f"'{CACHE_PLAYER_PKG}' not found in the same directory as this installer.")
    if not (MPV3_SRC_DIR / "meson.build").exists():
        errors.append(f"'{MPV3_SRC_PKG}' source tree not found at {MPV3_SRC_DIR} (expected meson.build).")
    if not shutil.which("meson"):
        errors.append("meson not found on PATH. Install meson before running this installer.")
    if not shutil.which("ninja"):
        errors.append("ninja not found on PATH. Install ninja before running this installer.")
    if errors:
        print("\nPre-install checks failed:")
        for e in errors:
            print(f"  [ERROR] {e}")
        sys.exit(1)
    print(f"  [OK] Source script        : {SOURCE_SCRIPT}")
    print(f"  [OK] cache-util source    : {CACHE_PLAYER_PARENT}")
    print(f"  [OK] mplayer3-bin source  : {MPV3_SRC_DIR}")
    print(f"  [OK] meson toolchain      : {shutil.which('meson')}")
    print(f"  [OK] ninja toolchain      : {shutil.which('ninja')}")
    print(f"  [OK] Config target        : {CONF_DIR}")
    print(f"  [OK] Build user assign    : {sudo_user or os.environ.get('USER', 'current')}")

# --- Main ---
def main():
    print(f"\n{'='*52}")
    print(f"  {APP_NAME} Installer")
    print(f"{'='*52}")

    print("\n[1/7] Pre-install checks...")
    preflight()

    # Clean old build
    if MPV3_BUILD_DIR.exists():
        print(f"\n[2/7] Cleaning previous build: {MPV3_BUILD_DIR}")
        shutil.rmtree(MPV3_BUILD_DIR)
        print(f"[OK] Build directory cleaned.")

    print(f"\n[3/7] Disabling support for Wayland")
    print(f"[*] Injecting (-Dwayland=disabled) argument during build.")

    print(f"\n[4/7] Configuring mplayer3-bin build (meson setup)...")
    run_as_user(["meson", "setup", "build", "-Dwayland=disabled"], cwd=MPV3_SRC_DIR, label="SETUP  ")

    print(f"\n[5/7] Compiling and installing mplayer3-bin...")
    run_as_user(["meson", "compile", "-C", "build"], cwd=MPV3_SRC_DIR, label="COMPILE")
    run_as_root(["meson", "install", "-C", "build"], cwd=MPV3_SRC_DIR, label="INSTALL")
    mplayer3_path = shutil.which("mplayer3-bin")
    if mplayer3_path:
        print(f"  [OK] mplayer3-bin installed: {mplayer3_path}")
    else:
        print(f"  [WARN] mplayer3-bin not found on PATH after install. Check meson install prefix.")

    print(f"\n[6/7] Setting up ~/.config/mplayer3/ ...")
    CONF_DIR.mkdir(parents=True, exist_ok=True)
    append_if_missing(MPV_CONF_FILE,   MPV_CONF,   MPLAYER3_MARKER)
    write_if_missing(INPUT_CONF_FILE,  INPUT_CONF)
    # Make sure newly-created config files are owned by the real user and not root
    if sudo_user:
        for p in (CONF_DIR, MPV_CONF_FILE, INPUT_CONF_FILE):
            try:
                if p.exists():
                    os.chown(p, REAL_UID, REAL_GID)
            except OSError:
                pass

    print(f"\n[7/7] Installing {APP_NAME} to {INSTALL_TARGET} ...")    
    shutil.copy2(SOURCE_SCRIPT, INSTALL_TARGET)
    os.chmod(INSTALL_TARGET, 0o755)
    print(f"  [OK] Installed: {INSTALL_TARGET}")

    # Install cache-util
    CACHE_PLAYER_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(CACHE_PLAYER_SOURCE, CACHE_PLAYER_TARGET)
    os.chmod(CACHE_PLAYER_TARGET, 0o755)
    print(f"  [OK] Installed: {CACHE_PLAYER_TARGET}")

    print(f"\nDone.")
    print(f"{'='*52}")
    print(f"  mplayer3 is ready. Try:")
    print(f"    mplayer3 -help")
    print(f"    mplayer3 -version")
    print(f"    mplayer3 -fs movie.mkv")
    print(f"    mplayer3 -cache-status")
    print(f"{'='*52}\n")

if __name__ == "__main__":
    main()
