#!/usr/bin/env python3

import os
import sys
import pwd
import shutil
from pathlib import Path

# --- Paths ---
APP_NAME        = "mplayer3"
INSTALL_TARGET  = Path("/usr/local/bin") / APP_NAME
SOURCE_SCRIPT   = Path(__file__).parent / APP_NAME

# Resolve real user home even when run via sudo
sudo_user = os.environ.get("SUDO_USER")
if sudo_user:
    REAL_HOME = Path(pwd.getpwnam(sudo_user).pw_dir)
else:
    REAL_HOME = Path.home()

CONF_DIR        = REAL_HOME / ".config" / "mpv"
MPV_CONF_FILE   = CONF_DIR / "mpv.conf"
INPUT_CONF_FILE = CONF_DIR / "input.conf"

# --- Marker (fingerprint to prevent duplicate appends) ---
MPLAYER3_MARKER = "# --- mplayer3 compatibility settings ---"

# --- Config file contents ---
MPV_CONF = """\
# --- mplayer3 compatibility settings ---
# Generated by install_mplayer3.py
# This block is safe to edit but do not remove the marker line above.

# Video
vo=gpu
hwdec=auto

# OSD (classic mplayer look)
osd-level=1
osd-font='Sans'
osd-font-size=30
osd-color='#CCFFFFFF'
osd-border-color='#99000000'
osd-bar-align-y=0.7
osd-bar-h=2
osd-bar-w=60

# Audio
volume=100
volume-max=200

# --- end mplayer3 settings ---
"""

INPUT_CONF = """\
# mplayer3 legacy keybindings
# Generated by install_mplayer3.py

ENTER   cycle fullscreen
ESC     quit
SPACE   cycle pause
f       cycle fullscreen
m       cycle mute
UP      add volume 5
DOWN    add volume -5
LEFT    seek -10
RIGHT   seek 10
PGUP    seek 600
PGDWN   seek -600
.       frame-step
,       frame-back-step
"""

# --- Helpers ---
def append_if_missing(path, content, marker):
    """
    For mpv.conf:
      - If file does not exist: create it fresh.
      - If file exists but marker is absent: append our block once, skipping duplicate option lines.
      - If file exists and marker is present: skip entirely (no duplicates).
    """
    if path.exists():
        existing = path.read_text()
        if marker in existing:
            print(f"  [SKIP]     {path}  (mplayer3 settings already present)")
        else:
            # Filter out any option lines that already exist in the file
            existing_lines = set(existing.splitlines())
            filtered_lines = []
            for line in content.splitlines():
                # Always keep comments, blank lines, and marker lines as-is
                if line.startswith("#") or line.strip() == "":
                    filtered_lines.append(line)
                # Only add option lines if not already present in the file
                elif line not in existing_lines:
                    filtered_lines.append(line)
            filtered_content = "\n".join(filtered_lines)
            with open(path, "a") as f:
                f.write(f"\n{filtered_content}\n")
            print(f"  [APPENDED] {path}  (mplayer3 settings added to existing file)")
    else:
        with open(path, "w") as f:
            f.write(content)
        print(f"  [CREATED]  {path}")

def write_if_missing(path, content):
    """
    For input.conf:
      - Keybindings are personal. Never overwrite an existing file.
      - Only create if it does not exist at all.
    """
    if path.exists():
        print(f"  [SKIP]     {path}  (already exists, keybindings not overwritten)")
    else:
        with open(path, "w") as f:
            f.write(content)
        print(f"  [CREATED]  {path}")

def preflight():
    errors = []
    if os.geteuid() != 0:
        errors.append("Must be run as root. Use: sudo python3 install_mplayer3.py")
    if not shutil.which("mpv3"):
        errors.append("mpv3 not found. Install it first: boxforge install mpv")
    if not SOURCE_SCRIPT.exists():
        errors.append(f"Source script '{APP_NAME}' not found in the same directory as this installer.")
    if errors:
        print("\nPre-install checks failed:")
        for e in errors:
            print(f"  [ERROR] {e}")
        sys.exit(1)
    print(f"  [OK] mpv3 found at : {shutil.which('mpv3')}")
    print(f"  [OK] Source script: {SOURCE_SCRIPT}")
    print(f"  [OK] Config target: {CONF_DIR}")

# --- Main ---
def main():
    print(f"\n{'='*52}")
    print(f"  {APP_NAME} Installer")
    print(f"{'='*52}")

    print("\n[1/4] Pre-install checks...")
    preflight()

    print(f"\n[2/4] Setting up ~/.config/mpv/ ...")
    CONF_DIR.mkdir(parents=True, exist_ok=True)
    append_if_missing(MPV_CONF_FILE,   MPV_CONF,   MPLAYER3_MARKER)
    write_if_missing(INPUT_CONF_FILE,  INPUT_CONF)

    print(f"\n[3/4] Installing {APP_NAME} to {INSTALL_TARGET} ...")
    shutil.copy2(SOURCE_SCRIPT, INSTALL_TARGET)
    os.chmod(INSTALL_TARGET, 0o755)
    print(f"  [OK] Installed: {INSTALL_TARGET}")

    print(f"\n[4/4] Done.")
    print(f"{'='*52}")
    print(f"  mplayer3 is ready. Try:")
    print(f"    mplayer3 -help")
    print(f"    mplayer3 -version")
    print(f"    mplayer3 -fs movie.mkv")
    print(f"{'='*52}\n")

if __name__ == "__main__":
    main()
